package com.journeyman.nexus.pitcraft.ai;

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.*;

class PitCommandTest {

    @Test
    void testRecordMechanics() {
        // 1. Test Constructor and Getters
        PitCommand cmd = new PitCommand(PitCommand.Action.EXTEND_TIME, "Brisket", 30);

        assertEquals(PitCommand.Action.EXTEND_TIME, cmd.action());
        assertEquals("Brisket", cmd.meatType());
        assertEquals(30, cmd.minutesModifier());

        // 2. Test Equals and HashCode (Generated by Record)
        PitCommand sameCmd = new PitCommand(PitCommand.Action.EXTEND_TIME, "Brisket", 30);
        PitCommand diffCmd = new PitCommand(PitCommand.Action.MARK_DONE, "Pork", 0);

        assertEquals(cmd, sameCmd);
        assertEquals(cmd.hashCode(), sameCmd.hashCode());
        assertNotEquals(cmd, diffCmd);

        // 3. Test toString (Generated by Record)
        String stringRep = cmd.toString();
        assertTrue(stringRep.contains("EXTEND_TIME"));
        assertTrue(stringRep.contains("Brisket"));
    }

    @Test
    void testActionEnum() {
        // 1. Test valueOf (String to Enum conversion)
        assertEquals(PitCommand.Action.START_COOK, PitCommand.Action.valueOf("START_COOK"));

        // 2. Test values() iteration (Covers the hidden values array)
        PitCommand.Action[] actions = PitCommand.Action.values();
        assertTrue(actions.length > 0);

        // 3. specific check for known values to ensure stability
        assertNotNull(PitCommand.Action.STATUS_CHECK);
        assertNotNull(PitCommand.Action.UNKNOWN);
    }
}