package com.journeyman.nexus.pitcraft.dto;

import org.junit.jupiter.api.Test;

import java.time.LocalDateTime;
import java.util.List;

import static org.junit.jupiter.api.Assertions.*;

class CookingPlanTest {

    @Test
    void testBuilder() {
        LocalDateTime now = LocalDateTime.now();
        List<String> ingredients = List.of("Salt", "Pepper");

        // 1. Use the Builder to create an object
        CookingPlan plan = CookingPlan.builder()
                .prepTime(now)
                .fireTime(now.plusHours(1))
                .servingTime(now.plusHours(10))
                .prepInstructions("Rub meat")
                .cookInstructions("Smoke at 225")
                .totalProcessHours(12.5)
                .shoppingList(ingredients)
                .build();

        // 2. Verify values
        assertEquals(now, plan.getPrepTime());
        assertEquals("Rub meat", plan.getPrepInstructions());
        assertEquals(12.5, plan.getTotalProcessHours());
        assertEquals(ingredients, plan.getShoppingList());
    }

    @Test
    void testToString() {
        CookingPlan plan = CookingPlan.builder()
                .prepInstructions("Test Instructions")
                .totalProcessHours(5.0)
                .build();

        String result = plan.toString();

        // Verify toString contains key fields and class name
        assertNotNull(result);
        assertTrue(result.contains("CookingPlan"));
        assertTrue(result.contains("Test Instructions"));
        assertTrue(result.contains("5.0"));
    }

    @Test
    void testEqualsAndHashCode() {
        LocalDateTime time = LocalDateTime.of(2025, 1, 1, 12, 0);

        // Object 1
        CookingPlan plan1 = CookingPlan.builder()
                .prepTime(time)
                .prepInstructions("Rub")
                .build();

        // Object 2 (Identical to 1)
        CookingPlan plan2 = CookingPlan.builder()
                .prepTime(time)
                .prepInstructions("Rub")
                .build();

        // Object 3 (Different)
        CookingPlan plan3 = CookingPlan.builder()
                .prepTime(time)
                .prepInstructions("Different")
                .build();

        // Test Equals
        assertEquals(plan1, plan2);
        assertNotEquals(plan1, plan3);

        // Test HashCode
        assertEquals(plan1.hashCode(), plan2.hashCode());
        assertNotEquals(plan1.hashCode(), plan3.hashCode());
    }

    @Test
    void testSetters() {
        // Since we tested Builder, we should also verify the setters generated by @Data work
        // (Builder often uses the constructor, so setters might be missed in coverage otherwise)
        CookingPlan plan = CookingPlan.builder().build();

        plan.setCookInstructions("Low and Slow");
        plan.setTotalProcessHours(8.0);

        assertEquals("Low and Slow", plan.getCookInstructions());
        assertEquals(8.0, plan.getTotalProcessHours());
    }

    @Test
    void testCanEqual() {
        // Lombok generation check
        CookingPlan plan1 = CookingPlan.builder().build();
        CookingPlan plan2 = CookingPlan.builder().build();
        assertTrue(plan1.canEqual(plan2));
    }
}